# Generated by Django 3.0.1 on 2020-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200107_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_access',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
