# Generated by Django 3.0.1 on 2020-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200124_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='cos',
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_access',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
