# Generated by Django 3.0.1 on 2020-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200124_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_access',
            field=models.DateTimeField(),
        ),
    ]
