# Generated by Django 3.0.1 on 2020-02-03 19:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200124_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_access_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 19, 23, 53, 89781, tzinfo=utc), verbose_name='RRRR-MM-DD HH:MM:SS'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_access',
            field=models.IntegerField(choices=[(15, '15 minut'), (30, '30 minut'), (60, '1 godzina')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_access',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='RRRR-MM-DD HH:MM:SS'),
        ),
    ]
