# Generated by Django 3.0.1 on 2020-02-03 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200203_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='second_chance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_access',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dostępu (RRRR-MM-DD HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_access_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 0, 15, 794130, tzinfo=utc), verbose_name='Data zakończenia (RRRR-MM-DD HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='exam.Subject', verbose_name='Przedmiot'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_access',
            field=models.IntegerField(choices=[(15, '15 minut'), (30, '30 minut'), (60, '1 godzina')], verbose_name='Dostępny przez'),
        ),
    ]
