# Generated by Django 3.0.1 on 2020-02-03 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200203_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_access_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 20, 4, 17, 774727, tzinfo=utc), verbose_name='Data zakończenia (RRRR-MM-DD HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='second_chance',
            field=models.BooleanField(default=True, verbose_name='Dodatkowe podejście'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_access',
            field=models.IntegerField(choices=[(15, '15 minut'), (30, '30 minut'), (60, '1 godzina')], null=True, verbose_name='Dostępny przez'),
        ),
    ]
